# Name of workflow
name: My Test Workflow

# Define the trigger event(s)
on: [push]

# Jobs run in paralle by default, each runs steps in sequence
jobs: 
  # Job to print something out
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, GutHub Actions!"

    