# Name of workflow
name: My Test Workflow

# Define the trigger event(s)
on: [push]

# Jobs run in paralle by default, each runs steps in sequence
jobs: 
  # Job to print something out
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, GutHub Actions!"

  # Job to build and test the C code
  build-and-test:
    needs: [say-hello]
    runs-on: ubuntu-latest
    steps:

        # Use github.com/actions/chackout to check out this repo
        - name: Check out this repo
          uses: actions/checkout@v3

        - name: Install dependencies
          run: sudo apt-get install -y build-essential python3

        - run: pwd

        - name: Run test
          run: python3 test.py

    